apiVersion: audit.k8s.io/v1
kind: Policy
omitStages:
  - "RequestReceived"
rules:
  - level: None
    resources:
    - group: ""
      resources: ["events", "endpoints", "nodes", "pods", "secrets", "bindings", "componentstatuses", "*/status"]
    - group: "authentication.k8s.io"
      resources: ["tokenreviews"]
    - group: "authorization.k8s.io"
      resources: ["subjectaccessreviews", "selfsubjectaccessreviews", "localsubjectaccessreviews", "selfsubjectrulesreviews"]
    - group: "coordination.k8s.io"
      resources: ["leases"]
    - group: "apps"
      resources: ["*/status"]
    - group: "networking.k8s.io"
      resources: ["*/status"]
  - level: None
    users: ["system:serviceaccount:kube-system:horizontal-pod-autoscaler"]
    verbs: ["update", "patch"]
    resources:
    - group: "apps"
      resources: ["*/scale"]
  - level: RequestResponse
    omitManagedFields: true
    verbs:
    - create
    - update
    - patch
    - delete
    - deletecollection
