"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$character"""

[directory]
style = "fg:#7dcfff"
format = "[ $path]($style) "
truncation_length = 4
truncate_to_repo = true

[git_branch]
symbol = " "
style = "fg:#9ece6a"
format = '[$symbol$branch]($style) '

[git_status]
style = "fg:#f7768e"
format = '[$all_status$ahead_behind]($style) '

[character]
success_symbol = "[❯](bold fg:#9ece6a)"
error_symbol = "[❯](bold fg:#f7768e)"
